### ISSUE TITLE
How I made my calculator app using functional components

### ISSUE THREAD

**Issue by Shaheryar0054** [Shaheryar0054/math-magicians#4]
- I first set up a create component using these commands; npx create-react-app, cd math-magic, and npm start, with linters set alongside.
- I created a component directory where I also created a calcultor.js file as a parent component.
- I created 2 children components(Button and Input) where I made the UX design for the app, I then imported them to the calculator.js 
   file that I finally used in the app.js.
- I downloaded 2 js(calculate and operate) files to implement my logic. I started with the useState which I imported, to initiate the app's 
   state.
-  I created an onClickhandler which I called in the buttons to implement the functions.

**Comment by tufoinnkuo10** [comment]
## Status: Approved :heavy_check_mark:

Hi @Shaheryar0054 

Your project is complete! Great job  🥇. There is nothing else to say other than keep up the good work🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Description 🆗 
- work well organized ✔️ 

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/XreQmk7ETCak0/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
